<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	</head>


    <style>

        .icon{
            width: 50px;
            height: 50px;
            margin-left: 50%;
        }
        .bt{
            background-color: #0b5004;
            padding: 10px;
            border-radius: 10%;
            width: 150px;
			height: 130px;
        }
        .botoes{
            display: grid;
            grid-template-columns: repeat(2, 1fr); 
            grid-template-rows: repeat(2, 1fr);   
            gap: 10px;   
            margin: 10%;
        }
        .bt h4{
            font-size: 1.4em;
            color: #fff;
        }

    </style>

	<body>



                        
        <!-- BOTOES -->
        <div class="botoes">   
			<a href="cadastro_produto">                    
                <div class=" bt cadastro_botao">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO PRODUTO</h4>
                </div>
			</a> 
			<a href="cadastro_pesticida"> 
                <div class=" bt cadastro_pesticida">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO PESTICIDA</h4>
                </div>
			</a> 
			<a href="plantacao"> 
                <div class=" bt plantacao">
                    <img class="icon" src="img/2.png" alt="">
                    <h4 class="text-center">PLANTAÇÃO</h4>
                </div>
			</a> 
			<a href="cadastro_canteiro"> 
                <div class=" bt cadastro_canteiro">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO CANTEIRO</h4>
                </div>
			</a> 
        </div>

        
	</body>

</html>