<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	</head>


    <style>

        body{
            color: #fff;
        }

        .icon{
            width: 50px;
            height: 50px;
            margin-left: 50%;
        }
        .bt{
            background-color: #0b5004;
            padding: 10px;
            border-radius: 10%;
            width: 150px;
			height: 130px;
        }
        .botoes{
            display: grid;
            grid-template-columns: repeat(2, 1fr); 
            grid-template-rows: repeat(2, 1fr);   
            gap: 10px;   
            margin: 10%;
        }
        .bt h4{
            font-size: 1.4em;
            color: #fff;
        }

        
        .InputContainer {
            margin: auto;
            height: 40px;
            display: flex;
            width: 300PX;
            align-items: center;
            justify-content: center;
            background-color: rgb(255, 255, 255);
            border-radius: 10px;
            overflow: hidden;
            cursor: pointer;
            padding-left: 15px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.075);
            }

            .input {
            width: 170px;
            height: 100%;
            border: none;
            outline: none;
            font-size: 0.9em;
            caret-color: rgb(255, 81, 0);
            }

            .labelforsearch {
            cursor: text;
            padding: 0px 12px;
            }

            .searchIcon {
            width: 13px;
            }

            .border {
            height: 40%;
            width: 1.3px;
            background-color: rgb(223, 223, 223);
            }

            .micIcon {
            width: 12px;
            }

            .micButton {
            padding: 0px 15px 0px 12px;
            border: none;
            background-color: transparent;
            height: 40px;
            cursor: pointer;
            transition-duration: .3s;
            }

            .searchIcon path {
            fill: rgb(114, 114, 114);
            }

            .micIcon path {
            fill: rgb(255, 81, 0);
            }

            .micButton:hover {
            background-color: rgb(255, 230, 230);
            transition-duration: .3s;
            }
            ion-icon{
                color: #0b5004;
            }
            .lupa{
                margin-top: 10px;
                background-color: transparent;
                border: none;
            }
            .camera{
                margin-left: 20px;
            }

            .alerta{
            margin: auto;
            width: 200px;
            background-color: #de0000;
            border-radius: 10px;
        }
        .aler{
            padding-top: 5px;
        }

        .tabela{
            position: relative;
            background-color: #0b5004;
            height: 100px;
            width: 90%;
            margin: auto;
            border-radius: 20px;
        }
        .infortext{

        }
        .numeracaocanteiro{
            position: absolute;
            background-color: #de0000;
            width: 50px;
            height: 50px;
            margin-top: 25px;
            margin-left: 20px;
            border-radius: 50%;
        }
        .numeracaocanteiro h3{
            margin-top: 6%;
        }
        .texto{
            margin-left: 60px;
            padding: 15px;
        }
        .texto p{
            position: relative;
            margin-left: 10PX;
        }

    </style>

	<body>

        <br>
        <form action="/pesquisa" method="post">
            <div class="InputContainer">
                <input type="number" name="cod" class="input" id="input" placeholder="Pesquisar">
                
                <label for="input" class="labelforsearch">
                    <button class="lupa" type="submit"><ion-icon name="search-outline"></ion-icon></button>
                    <a href=""></a>
            </label>
            <div class="border"></div>
            
            <a href=""><ion-icon class="camera" name="camera-outline"></ion-icon></a>
            
            </div>
        </form>

                        
        <!-- BOTOES -->
        <div class="botoes">   
			<a href="cadastro_produto">                    
                <div class=" bt cadastro_botao">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO PRODUTO</h4>
                </div>
			</a> 
			<a href="cadastro_pesticida"> 
                <div class=" bt cadastro_pesticida">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO PESTICIDA</h4>
                </div>
			</a> 
			<a href="plantacao"> 
                <div class=" bt plantacao">
                    <img class="icon" src="img/2.png" alt="">
                    <h4 class="text-center">PLANTAÇÃO</h4>
                </div>
			</a> 
			<a href="cadastro_canteiro"> 
                <div class=" bt cadastro_canteiro">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO CANTEIRO</h4>
                </div>
			</a> 
        </div>

        <!-- ALERTA -->

        <div class="alerta">
            
            <h3 class="text-center"> <ion-icon class="aler" name="alert-circle-outline"></ion-icon>   ALERTA     <ion-icon class="aler"  name="alert-circle-outline"></ion-icon></h3>
        </div>



        <!-- PARTE 2 -->

        <?php foreach ($this->view->cod as $key => $valor) { ?>

    <br>
    <div class="tabela">
        
        <div class="infortext">
            <div class="numeracaocanteiro">
                <h3 class="text-center"><?php echo $valor['canteiro']; ?></h3>
            </div>
            <div class="texto">
                <p> COLETAR DIA <span id="resultado_<?php echo $key; ?>"></span>  </p>
                <p> PESTICIDA FALTA <span id="falta_<?php echo $key; ?>"></span> DIAS </p>
            </div>
        </div>
    </div>
    <br>


    <script>
    var data_plantada_str_<?php echo $key; ?> = <?php echo json_encode($valor['dat']); ?>;
    var tp_plantacao_<?php echo $key; ?> = <?php echo json_encode($valor['tp_plantacao']); ?>;
    var carencia_<?php echo $key; ?> = <?php echo json_encode($valor['carencia']); ?>;

    var dia_plantado_<?php echo $key; ?> = <?php echo (new DateTime($valor['dat']))->format('d'); ?>;

    var hoje_<?php echo $key; ?> = new Date();
    var dia_hoje_<?php echo $key; ?> = hoje_<?php echo $key; ?>.getDate();

    var faltadias_<?php echo $key; ?> = ((dia_hoje_<?php echo $key; ?> - dia_plantado_<?php echo $key; ?>) - carencia_<?php echo $key; ?>);

    // Converte a string da data para obter ano, mês e dia
    var partesDataPlantada_<?php echo $key; ?> = data_plantada_str_<?php echo $key; ?>.split("-");
    var ano_<?php echo $key; ?> = parseInt(partesDataPlantada_<?php echo $key; ?>[0]);
    var mes_<?php echo $key; ?> = parseInt(partesDataPlantada_<?php echo $key; ?>[1]) - 1; // Mês começa do zero
    var dia_<?php echo $key; ?> = parseInt(partesDataPlantada_<?php echo $key; ?>[2]);

    // Converte a string da data plantada para um objeto Date
    var data_plantada_<?php echo $key; ?> = new Date(ano_<?php echo $key; ?>, mes_<?php echo $key; ?>, dia_<?php echo $key; ?>);

    // Adiciona o tempo de plantação à data plantada
    data_plantada_<?php echo $key; ?>.setDate(data_plantada_<?php echo $key; ?>.getDate() + parseInt(tp_plantacao_<?php echo $key; ?>));

    // Formata a data para exibir dia e mês
    var diaFormatado_<?php echo $key; ?> = data_plantada_<?php echo $key; ?>.getDate();
    var mesFormatado_<?php echo $key; ?> = data_plantada_<?php echo $key; ?>.toLocaleString('pt-BR', { month: 'short' });

    // Concatena dia e mês
    var resultadoFormatado_<?php echo $key; ?> = diaFormatado_<?php echo $key; ?> + ' ' + mesFormatado_<?php echo $key; ?>;

    // Seleciona o elemento <span> e atribui o novo valor
    document.getElementById('resultado_<?php echo $key; ?>').innerText = resultadoFormatado_<?php echo $key; ?>;
    document.getElementById('falta_<?php echo $key; ?>').innerText = faltadias_<?php echo $key; ?>;
</script>


<?php } ?>

        
	</body>

</html>