<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	</head>


    <style>

        body{
            color: #fff;
        }

        .icon{
            width: 100px;
            height: 100px;
            margin-left: 50%;
            margin-top: 5%;
        }
        .bt{
            background-color: #0b5004;
            padding: 10px;
            border-radius: 10%;
            width: 100%;
			height: 200px;
        }
        .botoes{
            display: grid;
            grid-template-columns: repeat(2, 1fr); 
            grid-template-rows: repeat(2, 1fr);   
            gap: 10px;   
            margin: 10%;

        }
        .bt h4{
        
            font-size: 2em;
            color: #fff;
        }

        
        .InputContainer {
            margin: auto;
            height: 6%;
            display: flex;
            width: 80%;
            align-items: center;
            justify-content: center;
            background-color: rgb(255, 255, 255);
            border-radius: 10px;
            overflow: hidden;
            cursor: pointer;
            padding-left: 15px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.075);
            }

            .input {
            width: 170px;
            height: 100%;
            border: none;
            outline: none;
            font-size: 2em;
            caret-color: rgb(255, 81, 0);
            }

            .labelforsearch {
            cursor: text;
            padding: 0px 12px;
            }

            .searchIcon {
            width: 13px;
            }

            .border {
            height: 40%;
            width: 1.3px;
            background-color: rgb(223, 223, 223);
            }

            .micIcon {
            width: 12px;
            }

            .micButton {
            padding: 0px 15px 0px 12px;
            border: none;
            background-color: transparent;
            height: 40px;
            cursor: pointer;
            transition-duration: .3s;
            }

            .searchIcon path {
            fill: rgb(114, 114, 114);
            }

            .micIcon path {
            fill: rgb(255, 81, 0);
            }

            .micButton:hover {
            background-color: rgb(255, 230, 230);
            transition-duration: .3s;
            }
            ion-icon{
                color: #0b5004;
                width: 70px;
                height: 70px;
            }
            .lupa{
                margin-top: 10px;
                background-color: transparent;
                border: none;
                margin-left: 300px;
            }
            .camera{
                margin-left: 20px;
            }

            .alerta{
            margin: auto;
            width: 70%;
            background-color: #de0000;
            border-radius: 10px;
        }
        .alerta h3{
            font-size: 5em;
        }
        .aler{
            padding-top: 5px;
        }

        .tabela{
            position: relative;
            background-color: #0b5004;
            height: 15%;
            width: 90%;
            margin: auto;
            border-radius: 20px;
        }
        .numeracaocanteiro{
            position: absolute;
            background-color: #de0000;
            width: 150px;
            height: 150px;
            margin-top: 6%;
            margin-left: 20px;
            border-radius: 50%;
        }
        .numeracaocanteiro h1{
            margin-top: 10%;
            color: #fff;
            font-size: 5em;
        }
        .texto{
            margin-left: 20%;
            padding: 15px;
        }
        .texto p{
            position: relative;
            margin-left: 10PX;
            font-size: 2.5em;
            color: #fff;
        }
        .texto .pri {
            margin-top: 6%;
        }
        .fechar{
            color: #fff;
            position: absolute;
            font-size: 3em;
            margin-left: 94%;
        }

    </style>

	<body onLoad="carregarDados()" id="pri">

        <br>
        <form action="/pesquisa" method="post">
            <div class="InputContainer">
                <input type="number" name="cod" class="input" id="input" placeholder="Pesquisar">
                
                <label for="input" class="labelforsearch">
                    <button class="lupa" type="submit"><ion-icon name="search-outline"></ion-icon></button>
                    <a href=""></a>
            </label>
            <div class="border"></div>
            
            <a href=""><ion-icon class="camera" name="camera-outline"></ion-icon></a>
            
            </div>
        </form>

		<!-- script -->
		<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

            <script src="../script.js"></script>
        <!-- BOTOES -->
        <div class="botoes">                 
                <div id="cadastro_produto" class=" bt cadastro_botao">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO PRODUTO</h4>
                </div>

                <div id="cadastro_pesticida" class=" bt cadastro_pesticida">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO PESTICIDA</h4>
                </div>

                <div id="plantacao" class=" bt plantacao">
                    <img class="icon" src="img/2.png" alt="">
                    <h4 class="text-center">PLANTAÇÃO</h4>
                </div>

                <div id="cadastro_canteiro" class=" bt cadastro_canteiro">
                    <img class="icon" src="img/1.png" alt="">
                    <h4 class="text-center">CADASTRO CANTEIRO</h4>
                </div>

        </div>

        <!-- ALERTA -->

        <div class="alerta">
            
            <h3 class="text-center"> <ion-icon class="aler" name="alert-circle-outline"></ion-icon>   ALERTA     <ion-icon class="aler"  name="alert-circle-outline"></ion-icon></h3>
        </div>



        <!-- PARTE 2 -->

        <?php foreach ($this->view->cod as $key => $valor) { ?>

    <br>

    <!-- <div class="ta" id="ta"> -->
    <a class="fechar" data-id="<?php echo $valor['id']; ?>">X</a>
        <div class="infortext">
            <div class="numeracaocanteiro">
                <a href="/coletar?id=<?php echo $valor['id'] ?>"><h1  id="canterioo" class="text-center"><?php echo $valor['canteiro']; ?></h1></a>
            </div>
            <div class="texto">
            <a href="/regacao?id=<?php echo $valor['id']; ?>&canteiro=<?php echo $valor['canteiro']; ?>">
                <p class="pri"> COLETAR DIA <span id="resultado_<?php echo $key; ?>"></span>  </p>
                <p> PESTICIDA VENCE NO DIA <span id="falta_<?php echo $key; ?>"></span> </p>
            </a>
            </div>

    </div>
    </div>
    <br>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>


        function carregarDados() {


            $.ajax({
            type: 'GET',
            url: '/fechar',
            data: `id=0`,
            dataType: 'json',
            success: response => { 

                if (response.status === 'success') {
                    var dados = response.data;

                    $('.ta').html(''); // Limpa o conteúdo atual

                    dados.forEach(function(item) {

                        console.log(item)


                        var html = `
                        <br>
                        <div class="tabela" id="tabelaPlantacao">
                                <a class="fechar" data-id="${item.id}">X</a>
                                <div class="infortext">
                                    <div class="numeracaocanteiro">
                                        <a href="/coletar?id=${item.id}"><h1 class="text-center">${item.canteiro}</h1></a>
                                    </div>
                                    <div class="texto">
                                        <a href="/regacao?id=${item.id}&canteiro=${item.canteiro}">
                                            <p class="pri"> COLETAR DIA <span id="resultado_${item.id}"></span>  </p>
                                            <p> PESTICIDA VENCE NO DIA <span id="falta_${item.id}"></span> </p>
                                        </a>
                                    </div>
                                </div>
                                </div>
                            <br> <br> 
                        `;

                        $('#ta').append(html);
                    });
                } else { console.error('Erro: ' + response.message)}},
                error: erro => { console.log(erro); }
            });

        }

        //click

        $('.fechar').on('click', function(e) {
            e.preventDefault();
            var id = $(this).data("id");



            $.ajax({
            type: 'GET',
            url: '/fechar',
            data: `id=${id}`,
            dataType: 'json',
            success: response => { 

                console.log('certo')
                // location.reload();
                carregarDados();
           
                
           },
            error: erro => { console.log(erro); }
            });
        });




    </script>


    <script>
    var data_plantada_str_<?php echo $key; ?> = <?php echo json_encode($valor['dat']); ?>;
    var tp_plantacao_<?php echo $key; ?> = <?php echo json_encode($valor['tp_plantacao']); ?>;
    var carencia_<?php echo $key; ?> = <?php echo json_encode($valor['carencia']); ?>;


    var dia_plantado_<?php echo $key; ?> = <?php echo (new DateTime($valor['data_atu']))->format('d'); ?>;
    var carencia_<?php echo $key; ?> = <?php echo $valor['carencia']; ?>;

    var hoje_<?php echo $key; ?> = new Date();
    var dia_hoje_<?php echo $key; ?> = hoje_<?php echo $key; ?>.getDate();

    var faltadias_<?php echo $key; ?> = parseInt(dia_plantado_<?php echo $key; ?>) + parseInt(carencia_<?php echo $key; ?>) - dia_hoje_<?php echo $key; ?>;

    // Converte a string da data para obter ano, mês e dia
    var partesDataPlantada_<?php echo $key; ?> = data_plantada_str_<?php echo $key; ?>.split("-");
    var ano_<?php echo $key; ?> = parseInt(partesDataPlantada_<?php echo $key; ?>[0]);
    var mes_<?php echo $key; ?> = parseInt(partesDataPlantada_<?php echo $key; ?>[1]) - 1; // Mês começa do zero
    var dia_<?php echo $key; ?> = parseInt(partesDataPlantada_<?php echo $key; ?>[2]);

    // Converte a string da data plantada para um objeto Date
    var data_plantada_<?php echo $key; ?> = new Date(ano_<?php echo $key; ?>, mes_<?php echo $key; ?>, dia_<?php echo $key; ?>);

    // Adiciona o tempo de plantação à data plantada
    data_plantada_<?php echo $key; ?>.setDate(data_plantada_<?php echo $key; ?>.getDate() + parseInt(tp_plantacao_<?php echo $key; ?>));

    // Formata a data para exibir dia e mês
    var diaFormatado_<?php echo $key; ?> = data_plantada_<?php echo $key; ?>.getDate();
    var mesFormatado_<?php echo $key; ?> = data_plantada_<?php echo $key; ?>.toLocaleString('pt-BR', { month: 'short' });

    // Concatena dia e mês
    var resultadoFormatado_<?php echo $key; ?> = diaFormatado_<?php echo $key; ?> + ' ' + mesFormatado_<?php echo $key; ?>;

    // Seleciona o elemento <span> e atribui o novo valor
    document.getElementById('resultado_<?php echo $key; ?>').innerText = resultadoFormatado_<?php echo $key; ?>;
    document.getElementById('falta_<?php echo $key; ?>').innerText = faltadias_<?php echo $key; ?>;
</script>


<?php } ?>

        
	</body>

</html>