<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

	</head>


    <style>


        .tex{
            background-color: #fff;
            width: 90%;
            margin: auto;
            padding: 5px;
            border-radius: 20px;
        }
        .login{
            background: rgba(0, 0, 0, .5);
            border-radius: 10px;
            width: 400px;
            padding: 40px;
            margin: 4%;
        }
        .login h2{
            margin-bottom: 30px;
            font-size: 30px;
            color: #fff;
            text-align: center;
        }
        .login .box_user{
            position: relative;
        }
        .login .box_user input{
            width: 100%;
            padding: 10px 0;
            outline: none;
            border: 0;
            background: transparent;
            border-bottom: 1px solid #fff;
            color: #fff;
            font-size: 16px;
            margin-bottom: 30px;
        }
        .login .box_user label{
            position: absolute;
            top: 0;
            left: 0;
            padding: 10px 0;
            color: #fff;
            font-size: 16px;
            pointer-events: none;
            transition: .5s;
        }
        .login .box_user input:focus~label,
        .login .box_user input:valid~label {
            top: -20px;
            left: 0;
            color: #03e9f4;
            font-size: 12px;
        }
        .forget{
            font-size: 12px;
            color: #5b6b8b;
            display: flex;
            justify-content: end;
        }
        .btn{
            position: relative;
            display: inline-block;
            padding: 12px 20px;
            color:  #fff;
            text-decoration: none;
            font-size: 13px;
            text-transform: uppercase;
            letter-spacing: 4px;
            font-weight: 700;
            margin-top: 20px;
            transition: .5s;
            overflow: hidden;
            margin-left: 25%;
            background-color:  #0b5004;
        }
        .btn:hover{
            background-color:  #0b5004;
            box-shadow: 3px 4px 62px  #0b5004;

            border-radius: 5px;
            color: #fff;
        }
        .btn span{
            position: absolute;
            display: block;
        }
        .btn span:nth-child(1){
            top: 0;
            left: -100%;
            width: 100%;
            height: 4px;
            background: linear-gradient(90deg, transparent, #03e9f4);
            animation: btn1 1s linear infinite;
        }


       
        @media(max-width: 405px){
            .login{

            width: 90%;

        }
        }

        select{
            margin: 3% 50%;
            background-color: transparent;
        }
        .dat{
           
            margin: 10% 0%;
            background-color: transparent;
        }

        .t{
            margin-bottom: 20px;
            margin-top: 20px;
        }


    </style>

	<body>





        <!-- PARTE 2 -->
        <br>
      
        <div class="text-center tex">
            <h2 >PLANTAÇÃO</h2>
        </div>
      
        <form action="/cd_plantacao" method="post" class="login">
            <div class="box_user">

                <select name="canteiro" id="">
                    <option value=""></option>
                        <?php foreach($this->view->canteiro as $key => $valor ) { ?>

                        <option value="<?php echo $valor['canteiro'] ?>"><?php echo $valor['canteiro']  ?></option>

                        <?php } ?>
                </select>
                <label for="">CANTEIRO:</label>

            </div>
            <div class="box_user">

                <select name="produto" id="">
                    <option value=""></option>
                        <?php foreach($this->view->produto as $key => $valor ) { ?>

                            <option value="<?php echo $valor['produto'] ?>"><?php echo $valor['produto']  ?></option>

                        <?php } ?>
                </select>
                <label for="">PRODUTO:</label>

            </div>
            <div class="box_user">
                <input type="number" name="qtd" required>
                <label for="">QTD:</label>
            </div>
            <div class="box_user">
                <input class="dat" type="date" name="dat" required>
                <label for="">DIA DA PLANTAÇÃO:</label>
            </div>
            <div class="box_user">
                <input type="number" name="ml_usado" required>
                <label for="">ML USADO:</label>
            </div>
            <div class="box_user">
                <input type="number" name="carencia" required>
                <label for="">CARENCIA:</label>
            </div>
            <div class="box_user">

                <select name="pesticida" id="">
                    <option value=""></option>
                        <?php foreach($this->view->pesticida as $key => $valor ) { ?>

                            <option value="<?php echo $valor['pesticida'] ?>"><?php echo $valor['pesticida']  ?></option>

                        <?php } ?>
                </select>
                <label for="">PERTICIDA:</label>

            </div>
            <div class="box_user t">
                <input type="text" name="obs" required>
                <label for="">OBS:</label>
            </div>
            <button type="submit" class="btn">CADASTRAR</button>
        </form>


        
	</body>

</html>