<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

	</head>


    <style>

        .tex{
            background-color: #fff;
            width: 90%;
            height: 5%;
            margin: auto;
            padding: 5px;
            border-radius: 20px;
            position: relative;
        }
        .tex h1{
            color: #000;
            font-size: 4em;
        }
        .lista{
            color: #fff;
            padding: 40px;
            margin: 4%;
            position: relative;

            display: flex;
        }
        .lis{
            display: flex;
            margin-left: -10px;
            width: 90%;
            padding: 40px;
            border-radius: 0 10px 10px 0;
            background: rgba(0, 0, 0, .5);
        }
       
        .cod{
            z-index: 90;
            padding: 40px;
            border-radius: 20px;
            background-color: #de0000;
            
        }
        .edit{
            font-size: 4em;
            position: relative;
  
            color: #fff;
        }
        .delete{
            font-size: 4em;
            position: relative;
            color: #fff;
           margin-left: 20px;
        }
        .nome{
            margin-left: 5%;

        }
        .dias{
            margin-left: 10%;
            margin-right: 14px;
        }

    </style>

	<body>
        <br>
        <div class="text-center tex">
            <a href="cadastro_pesticida"><h1 >LISTA PESTICIDA</h1></a>
        </div>
      

    <?php foreach ($this->view->produto as $key => $valor) : ?>
        <div class="lista">
            <div class="cod">
                <h1><?php echo $valor['id']; ?></h1>
            </div>
            <div class="lis">
                <h1 class="nome"><?php echo $valor['tipo_pesticida']; ?></h1>
                <h1 class="dias"><?php echo $valor['nome']; ?></h1>

                <a href="/editarpesticida?id=<?php echo $valor['id'] ?>"><ion-icon class="edit" name="create-outline"></ion-icon></a>
                <a data-id="<?php echo $valor['id']; ?>" data-tabela="pesticida"  
                    class="fechar" href="/deletar?id=<?php echo htmlspecialchars($valor['id']); ?>&tabela=produto">
                    <ion-icon class="delete" name="trash-outline"></ion-icon>
                </a>

            </div>
        </div>
    <?php endforeach; ?>


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>

$('.fechar').on('click', function(e) {
    e.preventDefault();
    var id = $(this).data("id");
    var tabela = $(this).data("tabela");

    console.log(id);

    $.ajax({
        type: 'GET',
        url: '/deletar',
        data: { id: id, tabela: tabela },  // Combine os parâmetros em um objeto
        dataType: 'json',
        success: response => { 
            console.log('CHEGOU AQUI')
            location.reload();
        },
        error: erro => { console.log(erro); }
    });
});


    </script>
        
	</body>

</html>