<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	</head>

	<style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap');
      </style>

    <style>
        body {
            /*font-family: 'Lato', sans-serif;*/
            background-image: url("img/deliciosas-bananas-na-natureza.jpg");
            background-repeat: no-repeat;
            background-position: center;
            background-size:cover;
        }

        .na{
            padding: 0px 30px;
        }
        .biasi{
            width: 60%;
        }
        .linha{
            border-bottom: 2px solid black;
            width: 290px;
            margin-left: -50px;
            margin-top: -25px;
        }


    </style>

	<body>

	    <!-- NAV -->
		<nav class="na">
			<div class=" txt">
                <a href="/">
                <img class="biasi" src="img/3.png" alt=""></a>
                <div class="linha"></div>
			</div>
		</nav>




		<?= $this->content() ?>
	</body>

</html>